apiVersion: v1
kind: Service
metadata:
  name: mongodb-express-service
  namespace: default
  labels:
    app: mongodb-express
    tier: frontend
spec:
  type: ClusterIP
  selector:
    app: mongodb-express
    tier: frontend
  ports:
  - name: http
    protocol: TCP
    port: 8081
    targetPort: 8081

---
# NodePort service for external access to MongoDB Express
apiVersion: v1
kind: Service
metadata:
  name: mongodb-express-nodeport
  namespace: default
  labels:
    app: mongodb-express
    tier: frontend
    service-type: external
spec:
  type: NodePort
  selector:
    app: mongodb-express
    tier: frontend
  ports:
  - name: http
    protocol: TCP
    port: 8081
    targetPort: 8081
    nodePort: 30081
