apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: default
type: Opaque
data:
  # Note: These are encrypted credentials, managed by scripts/manage-credentials.sh
  # To view credentials: ./scripts/manage-credentials.sh --show
  mongodb-username: YWRtaW4=
  mongodb-password: bzUzUzloYTU4WTgzY2k5WjhkMkV5bVhq
  mongodb-root-password: T09DOHgyVmFPcVdqc3dRYWRkcnFhZnNvaEh4ZFR2WEI=
